#  Question 10

In [8]:
import numpy as np


data = np.array([(15, 5), (9, 4), (11, 3), (7, 2), (4, 1)])

leave_one_out_matrices = []

for i in range( len(data)):
    
    testing_point = data[i]

    
    training_matrix = np.delete(data, i, axis=0)

    
    leave_one_out_matrices.append(training_matrix)


for i, training_matrix in enumerate(leave_one_out_matrices):
    print(f"Result for iteration {i + 1} (Training with point {i + 1} removed):")
    print(training_matrix)


Result for iteration 1 (Training with point 1 removed):
[[ 9  4]
 [11  3]
 [ 7  2]
 [ 4  1]]
Result for iteration 2 (Training with point 2 removed):
[[15  5]
 [11  3]
 [ 7  2]
 [ 4  1]]
Result for iteration 3 (Training with point 3 removed):
[[15  5]
 [ 9  4]
 [ 7  2]
 [ 4  1]]
Result for iteration 4 (Training with point 4 removed):
[[15  5]
 [ 9  4]
 [11  3]
 [ 4  1]]
Result for iteration 5 (Training with point 5 removed):
[[15  5]
 [ 9  4]
 [11  3]
 [ 7  2]]
