# Question 11

In [2]:
import numpy as np

In [3]:
irises_data = np.load("irises.npy")
print(irises_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.

In [4]:
new_irises = np.load("new_irises.npy")
print(new_irises)

[[5.  3.6 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.8 4.  1.2 0.2]
 [5.1 3.8 1.5 0.3]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [5.  3.3 1.4 0.2]
 [6.5 2.8 4.6 1.5]
 [5.2 2.7 3.9 1.4]
 [5.6 2.9 3.6 1.3]
 [5.6 2.5 3.9 1.1]
 [6.4 2.9 4.3 1.3]
 [5.7 2.6 3.5 1. ]
 [5.4 3.  4.5 1.5]
 [5.5 2.5 4.  1.3]
 [5.6 2.7 4.2 1.3]
 [5.7 2.8 4.1 1.3]
 [6.5 3.  5.8 2.2]
 [7.2 3.6 6.1 2.5]
 [5.8 2.8 5.1 2.4]
 [6.  2.2 5.  1.5]
 [6.7 3.3 5.7 2.1]
 [7.2 3.  5.8 1.6]
 [6.1 2.6 5.6 1.4]
 [6.9 3.1 5.4 2.1]
 [6.7 3.3 5.7 2.5]
 [5.9 3.  5.1 1.8]]


In [5]:
t= np.array([[1,0,0],
            [0,1,0]])
v=np.array([[1,1,0],
           [0,0,0]])
distances = np.linalg.norm(t-v)
print(distances)


1.4142135623730951


# calculate distance

In [7]:
import timeit


def calculate_distance_loops():
    distances = []
    for new_point in new_irises:
        distance_list = []
        for data_point in irises_data:
            distance = np.sqrt(np.sum((data_point - new_point) ** 2))
            message = f"Distance of {new_point} from {data_point} is: {distance}"
            distance_list.append(message)
        distances.append(distance_list)
        
    print("calculate_distance_loops",distances)        


def calculate_distance_single_loop():
    distances = []
    for new_point in new_irises:
        distance_list = [np.sqrt(np.sum((data_point - new_point) ** 2)) for data_point in irises_data]
        distances.append(distance_list)
    print("calculate_distance_single_loop" ,distances)   


def calculate_distance_vectorized():
    distances = np.linalg.norm(irises_data[:, np.newaxis, :] - new_irises, axis=2)
    print("calculate_distance_vectorized",distances)

loops_time = timeit.timeit(calculate_distance_loops,number=1 )
single_loop_time = timeit.timeit(calculate_distance_single_loop,number=1 )
vectorized_time = timeit.timeit(calculate_distance_vectorized,number=1 )

print("Execution time with two loops :", loops_time)
print("Execution time with a single loop :", single_loop_time)
print("Execution time with vectorization :", vectorized_time)




calculate_distance_loops [['Distance of [5.  3.6 1.4 0.2] from [5.1 3.5 1.4 0.2] is: 0.1414213562373093', 'Distance of [5.  3.6 1.4 0.2] from [4.9 3.  1.4 0.2] is: 0.608276253029822', 'Distance of [5.  3.6 1.4 0.2] from [4.7 3.2 1.3 0.2] is: 0.5099019513592783', 'Distance of [5.  3.6 1.4 0.2] from [4.6 3.1 1.5 0.2] is: 0.6480740698407862', 'Distance of [5.  3.6 1.4 0.2] from [5.4 3.9 1.7 0.4] is: 0.6164414002968979', 'Distance of [5.  3.6 1.4 0.2] from [4.6 3.4 1.4 0.3] is: 0.4582575694955844', 'Distance of [5.  3.6 1.4 0.2] from [5.  3.4 1.5 0.2] is: 0.22360679774997916', 'Distance of [5.  3.6 1.4 0.2] from [4.4 2.9 1.4 0.2] is: 0.9219544457292886', 'Distance of [5.  3.6 1.4 0.2] from [5.4 3.7 1.5 0.2] is: 0.42426406871192884', 'Distance of [5.  3.6 1.4 0.2] from [4.8 3.4 1.6 0.2] is: 0.3464101615137758', 'Distance of [5.  3.6 1.4 0.2] from [4.8 3.  1.4 0.1] is: 0.640312423743285', 'Distance of [5.  3.6 1.4 0.2] from [4.3 3.  1.1 0.1] is: 0.9746794344808964', 'Distance of [5.  3.6 1.4