<h1> Question 2 <h1>

In [1]:
import numpy as np

create 10*10 matrix

In [2]:
random_matrix = np.random.randint(1, 11, size=(10, 10))

print(random_matrix)

[[ 1  1  6  7  7 10  4  3  6  7]
 [ 3 10  9 10  5  2  3  1  1  8]
 [ 2  6  5  6  8  4  4  8  1 10]
 [ 5  3  5  8  6  4  3  6 10 10]
 [ 8  1  1  1  4 10  8  8  9  6]
 [ 3  1  4  3 10  2  6  6  9 10]
 [10  3  4  8  4  5  2  8 10  6]
 [ 4  4  7  3  2  4  3  4  3  9]
 [ 3  2  9  4  5  9  6  3  2  4]
 [ 9  2  7  1  5  6  8  3  3  9]]


 find column_sums


In [4]:

column_sums = np.sum(random_matrix, axis=0)
print(column_sums)



[48 33 57 51 56 56 47 50 54 79]


 find row_sums


In [5]:

row_sums = np.sum(random_matrix, axis=1)

print(row_sums)

[52 52 54 60 56 54 60 43 47 53]
