# Question 3

In [1]:
import numpy as np

### create heights matrix

In [2]:
heights = np.array([140.0, 200.0, 175.0, 120.0, 150.0], dtype=np.float64)
print(heights)


[140. 200. 175. 120. 150.]


### create widths matrix

In [3]:
widths = np.array([7, 10, 15, 8, 12], dtype=np.float64)
print(widths)


[ 7. 10. 15.  8. 12.]


### find area

In [4]:
areas = heights * widths
print(areas)

[ 980. 2000. 2625.  960. 1800.]


### find indicators

In [6]:
indicators = np.arange(len(widths))
print(indicators)

[0 1 2 3 4]


### find plant info

In [7]:
info_plant = np.column_stack((indicators, heights, widths))
print(info_plant)

[[  0. 140.   7.]
 [  1. 200.  10.]
 [  2. 175.  15.]
 [  3. 120.   8.]
 [  4. 150.  12.]]


### find Identity matrix

In [8]:
matrix_identity = np.eye(3)
print(matrix_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### find diagonal matrix

In [9]:
matrix_diagonal = np.diag(areas)
print(matrix_diagonal)

[[ 980.    0.    0.    0.    0.]
 [   0. 2000.    0.    0.    0.]
 [   0.    0. 2625.    0.    0.]
 [   0.    0.    0.  960.    0.]
 [   0.    0.    0.    0. 1800.]]


### find sums_squared

In [18]:
sums_squared = np.fromfunction(lambda i, j: (i + j) ** 2, (5, 3), dtype=np.float64)
print(sums_squared)

[[ 0.  1.  4.]
 [ 1.  4.  9.]
 [ 4.  9. 16.]
 [ 9. 16. 25.]
 [16. 25. 36.]]
