# Question 4

In [29]:
import numpy as np


### 1. find dimensions of array

create my array

In [30]:
x = np.random.randint(0,4,size=(4, 5))
print(x)

[[3 3 3 3 0]
 [0 0 1 2 1]
 [2 0 0 3 1]
 [2 0 0 1 3]]


dimensions

In [31]:
rows, columns = x.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 4
Number of columns: 5


type

In [32]:
array_type = x.dtype

print("Data type of the array:", array_type)



Data type of the array: int32


size

In [33]:
size =x.size;
print(size)

20


### 2.  reshape array

In [34]:
reshape= x.reshape(2,-1)
print(reshape)

[[3 3 3 3 0 0 0 1 2 1]
 [2 0 0 3 1 2 0 0 1 3]]


### 3. find first row

In [35]:
first_row=x[0,:]
print(first_row)

[3 3 3 3 0]


### 4. find first column

In [36]:
first_column=x[:,0]
print(first_column)

[3 0 2 2]


### 5. find last row

In [37]:
last_row=x[-1,:]
print(last_row)

[2 0 0 1 3]


### 6. find [1,1]

In [38]:
first=x[1,1]
print(first)

0


### 7. find columns_1_to_3

In [39]:
columns_1_to_3 = x[:, 1:4]
print(columns_1_to_3)

[[3 3 3]
 [0 1 2]
 [0 0 3]
 [0 0 1]]


### 8. find mask

In [43]:
mask=x>=2
print(mask)

[[ True  True  True  True False]
 [False False False  True False]
 [ True False False  True False]
 [ True False False False  True]]


### 9. find result

In [50]:
result = np.where(mask)
print("list of result:")
for row, col in zip(result[0], result[1]):
    print(f"({row},{col})")

list of result:
(0,0)
(0,1)
(0,2)
(0,3)
(1,3)
(2,0)
(2,3)
(3,0)
(3,4)


### 10. find depth

In [51]:
depth_01 = x[0, 1]

depth_02 = x[0, 2]

print("(0, 1):", depth_01)
print("(0, 2):", depth_02)

(0, 1): 3
(0, 2): 3
