# Question 5

### 1. create 100 number between 0  an 1

In [3]:
import numpy as np

In [9]:
num_elements = 100
start = 0
end = 1
equal_spacing_array = np.linspace(start, end, num_elements)

# Display the array
print(equal_spacing_array)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

### 2. cosine_similarity

In [18]:
def cosine_similarity(vector_a, vector_b):
    dot_product = np.dot(vector_a, vector_b)
    norm_a = np.linalg.norm(vector_a)
    norm_b = np.linalg.norm(vector_b)
    similarity = dot_product / (norm_a * norm_b)
    return similarity

#example
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

similarity = cosine_similarity(vector1, vector2)
print(f"Cosine Similarity: {similarity}")

Cosine Similarity: 0.9746318461970762


### 3. age index

In [19]:
# Create a NumPy array containing the ages of a group of people
ages = np.array([25, 32, 20, 18, 30, 35, 22, 28, 16, 40])

# Define a logical condition to filter ages between 18 and 30
logical_indices = (ages >= 18) & (ages <= 30)


selected_ages = ages[logical_indices]
print(selected_ages)

[25 20 18 30 22 28]


### 4. check cumulative sum

In [28]:
import timeit

large_array = np.random.rand(1000000)

# Calculate cumulative sum using a for loop
def sum_with_for_loop(arr):
    result = 0
    for num in arr:
        result += num
    return result

# Calculate cumulative sum using a vectorized approach
def sum_with_cumulativeSum(arr):
    return np.cumsum(arr)

# Measure the execution time of the for loop approach
for_loop_time = timeit.timeit('sum_with_for_loop(large_array)', globals=globals(), number=1)

# Measure the execution time of the vectorized approach
cumulativeSum_time = timeit.timeit('sum_with_cumulativeSum(large_array)', globals=globals(), number=1)

print(f"Time taken for the for loop approach: {for_loop_time} seconds")
print(f"Time taken for the cumulativeSum time approach: {cumulativeSum_time} seconds")

Time taken for the for loop approach: 0.18387540000003355 seconds
Time taken for the cumulativeSum time approach: 0.008232500000303844 seconds


### 5. binery mask

In [30]:

intensity_image = np.array([[100, 150, 200, 50],
                            [75, 180, 120, 220],
                            [30, 90, 60, 170]])

# Minimum threshold 
threshold = 100

# Create a binary mask
binary_mask = np.greater(intensity_image, threshold)

print(binary_mask)

[[False  True  True False]
 [False  True  True  True]
 [False False False  True]]


### 6. SVD

In [34]:
import numpy as np


np.random.seed(0)
data = np.random.rand(100, 100)  # Original dataset


# Perform Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(data, full_matrices=False)


new_dimension = 10

# Create a dimension-reduced matrix by selecting the first 'new_dimension' columns of 'U' and 'VT'
reduced_data = np.dot(U[:, :new_dimension], np.dot(np.diag(S[:new_dimension]), VT[:new_dimension, :]))

print(reduced_data)


[[0.17807744 0.92633902 0.84409519 ... 0.28923234 0.6993527  0.23039155]
 [0.5886095  0.46277642 0.45663114 ... 0.61796199 0.34842949 0.48346788]
 [0.4522074  0.60179385 0.70011677 ... 0.53475454 0.81542011 0.77641191]
 ...
 [0.74052023 0.34630792 0.91755738 ... 0.77353749 0.71611046 0.71199253]
 [0.29372178 0.9237702  0.78880819 ... 0.55638273 0.82549268 0.18545507]
 [0.42926498 0.54045102 0.25781662 ... 0.5905072  0.21283862 0.5441559 ]]


### 7. pearson_correlation

In [35]:
import numpy as np

def pearson_correlation(x, y):
    # Calculate the means of the data
    mean_x = np.mean(x)
    mean_y = np.mean(y)
    
    # Calculate the numerator, the sum of cross-deviations from the mean
    numerator = np.sum((x - mean_x) * (y - mean_y))
    
    # Calculate the denominators, the square root of the sum of squared deviations from the mean for both arrays
    denominator_x = np.sqrt(np.sum((x - mean_x) ** 2))
    denominator_y = np.sqrt(np.sum((y - mean_y) ** 2))
    
    # Calculate the Pearson correlation coefficient
    r = numerator / (denominator_x * denominator_y)
    
    return r

# Example: Two real data series
data_series1 = np.array([1, 2, 3, 4, 5])
data_series2 = np.array([2, 3, 4, 5, 6])

# Calculate the Pearson correlation coefficient between two data series
correlation = pearson_correlation(data_series1, data_series2)

print(f"Pearson Correlation: {correlation}")


Pearson Correlation: 0.9999999999999998


### 8. read CSV

In [10]:


# Name of the CSV file
csv_file = "city.csv"

# Reading data from the CSV file using NumPy's loadtxt function
data = np.loadtxt(csv_file, delimiter=',', dtype=str)

# # Extracting the numeric values from the loaded data
numeric_data = data.astype(float)

# # Saving the numeric data as a NumPy array
binary_file = "binery.npy"
np.save(binary_file, numeric_data)


print("CSV data has been read and saved as a binary file.")


CSV data has been read and saved as a binary file.


### 9 . Fourier transform 

In [13]:
import numpy as np
import matplotlib.pyplot as plt

def analyze_audio_signal(audio_signal, sample_rate):
    # Perform the Fourier transform 
    signal_length = len(audio_signal)
    fft_result = np.fft.fft(audio_signal)
    freq = np.fft.fftfreq(signal_length, 1 / sample_rate)

    # Calculate the magnitude 
    magnitude = np.abs(fft_result)
    print("Magnitude :",magnitude,)
    print("Frequency :",freq)

   
audio_signal = np.array([1.0, 2.0, 1.0, -1.0, 0.0, 1.0, 2.0, 1.0])
sample_rate = 44100  

analyze_audio_signal(audio_signal, sample_rate)


Magnitude : [7.         3.55764729 3.60555128 1.15894165 1.         1.15894165
 3.60555128 3.55764729]
Frequency : [     0.    5512.5  11025.   16537.5 -22050.  -16537.5 -11025.   -5512.5]
