# Question 6

### 1 . Standardized Data in column

In [32]:
import numpy as np

In [33]:
sensor_data = np.array([[1.2, 3.5, 2.4, 1.8],
                        [4.1, 2.2, 3.9, 4.8],
                        [2.8, 1.9, 4.5, 3.2]])

column_means = np.mean(sensor_data, axis=0)
column_stds = np.std(sensor_data, axis=0)
data_standardized = (sensor_data - column_means) / column_stds

print("Data Standardized:")
print(data_standardized)

Data Standardized:
[[-1.26472371  1.39204455 -1.35873244 -1.19664225]
 [ 1.1804088  -0.48001536  0.33968311  1.25103507]
 [ 0.08431491 -0.91202919  1.01904933 -0.05439283]]


### 2 . Standardized Data in Row

In [34]:



data_sensor = np.array([[1.2, 3.5, 2.4, 1.8],
                        [4.1, 2.2, 3.9, 4.8],
                        [2.8, 1.9, 4.5, 3.2]])


row_means = np.mean(data_sensor, axis=1)
row_stds = np.std(data_sensor, axis=1)


data_standardized_row = (((data_sensor.T - row_means)) / row_stds).T


print("Data Standardized by Row:")
print(data_standardized_row)


Data Standardized by Row:
[[-1.20640427  1.50064921  0.20597146 -0.5002164 ]
 [ 0.36639675 -1.62261416  0.15702718  1.09919024]
 [-0.32071349 -1.28285396  1.49666295  0.1069045 ]]


### 3. sum

In [35]:
total_sum = np.sum(data_sensor)
print("sum",total_sum)

sum 36.3


###  4. column sum

In [36]:
column_sums  = np.sum(data_sensor,axis=0)
print("sum : ",column_sums )

sum :  [ 8.1  7.6 10.8  9.8]


###  5. Row sum

In [37]:
Row_sums  = np.sum(data_sensor,axis=1)
print("sum : ",Row_sums )

sum :  [ 8.9 15.  12.4]


### 6 . hstack

In [38]:
data_combined = np.hstack((data_sensor, data_standardized))
print(data_combined)

[[ 1.2         3.5         2.4         1.8        -1.26472371  1.39204455
  -1.35873244 -1.19664225]
 [ 4.1         2.2         3.9         4.8         1.1804088  -0.48001536
   0.33968311  1.25103507]
 [ 2.8         1.9         4.5         3.2         0.08431491 -0.91202919
   1.01904933 -0.05439283]]


### 7. divide into 3 array

In [39]:
num_columns = data_combined.shape[1]

# Split into three arrays
split_size = num_columns // 3
A = data_combined[:, :split_size]
B = data_combined[:, split_size:2 * split_size]
C = data_combined[:, 2 * split_size:]

# Display arrays A, B, and C
print("Array A:")
print(A)
print("Array B:")
print(B)
print("Array C:")
print(C)

Array A:
[[1.2 3.5]
 [4.1 2.2]
 [2.8 1.9]]
Array B:
[[2.4 1.8]
 [3.9 4.8]
 [4.5 3.2]]
Array C:
[[-1.26472371  1.39204455 -1.35873244 -1.19664225]
 [ 1.1804088  -0.48001536  0.33968311  1.25103507]
 [ 0.08431491 -0.91202919  1.01904933 -0.05439283]]


### 8 . Dot

In [41]:
data_sensor_transpose = data_sensor.T

product_matrix = np.dot(data_sensor_transpose, data_sensor)

# Display 
print("Matrix Product:")
print(product_matrix)

Matrix Product:
[[26.09 18.54 31.47 30.8 ]
 [18.54 20.7  25.53 22.94]
 [31.47 25.53 41.22 37.44]
 [30.8  22.94 37.44 36.52]]


### 9. log

In [42]:
data_log = np.log(data_sensor)


print("Array data_log:")
print(data_log)



Array data_log:
[[0.18232156 1.25276297 0.87546874 0.58778666]
 [1.41098697 0.78845736 1.36097655 1.56861592]
 [1.02961942 0.64185389 1.5040774  1.16315081]]


### exp

In [44]:
combined_data = np.exp(data_sensor) 
print(combined_data)

[[  3.32011692  33.11545196  11.02317638   6.04964746]
 [ 60.3402876    9.0250135   49.40244911 121.51041752]
 [ 16.44464677   6.68589444  90.0171313   24.5325302 ]]


### 10 . vstack

In [45]:
data_stacked = np.vstack((data_sensor, data_sensor))

# Split the data_sensor array into two arrays, 1_split and 2_split
split_size = len(data_sensor) // 2
split_1 = data_sensor[:split_size, :]
split_2 = data_sensor[split_size:, :]

# Display the arrays
print("Array data_stacked:")
print(data_stacked)

print("Array 1_split:")
print(split_1)

print("Array 2_split:")
print(split_2)

Array data_stacked:
[[1.2 3.5 2.4 1.8]
 [4.1 2.2 3.9 4.8]
 [2.8 1.9 4.5 3.2]
 [1.2 3.5 2.4 1.8]
 [4.1 2.2 3.9 4.8]
 [2.8 1.9 4.5 3.2]]
Array 1_split:
[[1.2 3.5 2.4 1.8]]
Array 2_split:
[[4.1 2.2 3.9 4.8]
 [2.8 1.9 4.5 3.2]]
