# Question 8 

### 1 . standard

In [1]:
import numpy as np

In [3]:

exp2_data = np.array([[10, 11, 12],
[13, 14, 15],
[16, 17, 18]])


exp1_data = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


exp3_data = np.array([[19, 20, 21],
[22, 23, 24],
[25, 26, 27]])


def standardize_data(data):
    column_means = np.mean(data, axis=0)
    column_stds = np.std(data, axis=0)
    standardized_data = (data - column_means) / column_stds
    return standardized_data


std_exp1_data = standardize_data(exp1_data)
std_exp2_data = standardize_data(exp2_data)
std_exp3_data = standardize_data(exp3_data)



print("std_exp1_data : ")
print(std_exp1_data)


print("std_exp2_data : ")
print(std_exp2_data)


print("std_exp3_data : ")
print(std_exp3_data)

std_exp1_data : 
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
std_exp2_data : 
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
std_exp3_data : 
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


### 2 . combine and splite

In [8]:
combined_data = np.hstack((std_exp1_data, std_exp2_data, std_exp3_data))

print("combined_data :")
print(combined_data)

spite_1=combined_data[:2,:]
spite_2=combined_data[2:3,:]

print("\n \n spite_1 : \n")
print(spite_1)

print("\n \n spite_2 : \n")
print(spite_2)

combined_data :
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487 -1.22474487 -1.22474487
  -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487  1.22474487  1.22474487
   1.22474487  1.22474487  1.22474487]]

 
 spite_1 : 

[[-1.22474487 -1.22474487 -1.22474487 -1.22474487 -1.22474487 -1.22474487
  -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]]

 
 spite_2 : 

[[1.22474487 1.22474487 1.22474487 1.22474487 1.22474487 1.22474487
  1.22474487 1.22474487 1.22474487]]


### 3 . inner_product

In [9]:
inner_product = np.dot(spite_1, spite_2.T)  


print("inner_product :")
print(inner_product)

inner_product :
[[-13.5]
 [  0. ]]


### 4 . scalar_result

In [10]:
# Sum them into a scalar result
scalar_result = np.sum(inner_product)

print("Result as a scalar value:")
print(scalar_result)

Result as a scalar value:
-13.500000000000002
